Repository spectrocloud/cluster-api-provider-maas, pull requests merged in 2021-07, with the labels that each got.

#4 bump controller-gen to 0.6.1 move to hack/tools
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_maasclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_maasmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_maasmachinetemplates.yaml
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: ok-to-test, size/XL

#3 Setup prow
  Makefile
  pkg/maas/dns/dns.go
  prow/functions.sh
  prow/periodics.sh
  prow/postsubmit.sh
  prow/presubmit.sh
  prow/release_build.sh
Labels: ok-to-test, size/L

#5 Testing CI
  README.md
Labels: size/XS
