Repository spectrocloud/cluster-api-provider-maas, pull requests merged in 2021-08, with the labels that each got.

#7 add infrastructure-components make fmt
  .gitignore
  Makefile
  clusterctl-settings.json
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_pull_policy.yaml
  config/default/namespace.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  hack/boilerplate.go.txt
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  metadata.yaml
  pkg/maas/client/mock/clienset_mock.go
  pkg/maas/machine/machine_test.go
  pkg/maas/scope/cluster_test.go
  prow/functions.sh
Labels: approved, ok-to-test, size/L

#8 verify e2e working examples
  Makefile
  README.md
  examples/cluster3-baremetal.yaml
  go.mod
  go.sum
  pkg/maas/machine/machine.go
Labels: size/L, needs-ok-to-test, approved

#9 Release V0.1.0
  Makefile
  clusterctl-settings.json
  prow/functions.sh
  prow/release_build.sh
Labels: size/M

#10 dns record use uuid in domain name
  go.mod
  go.sum
  pkg/maas/dns/dns_test.go
  pkg/maas/scope/cluster.go
  pkg/maas/scope/cluster_test.go
Labels: ok-to-test, size/M, approved

#12 Changelog
  CHANGELOG.md
  Makefile
  clusterctl-settings.json
  prow/functions.sh
Labels: size/S

#13 add image generation steps
  README.md
  image-generation/Dockerfile
  image-generation/Makefile
  image-generation/README.md
  image-generation/buildmaasimage.sh
  image-generation/pod.yaml
  image-generation/secret.yaml
Labels: size/L, needs-ok-to-test, approved

#14 [readme] image generation link
  README.md
Labels: needs-ok-to-test, size/XS, approved

#15 doc fix
  README.md
  examples/cluster1.yaml
Labels: size/M, approved

#16 fix example yaml
  examples/cluster1.yaml
Labels: approved, size/S

#17 example cleanup
  README.md
  examples/cluster1-upgrade.yaml
  examples/cluster2-multi-az-cp.yaml
  examples/cluster2-multi-az-workers.yaml
  examples/cluster3-baremetal.yaml
  examples/sample-cp-only.yaml
  examples/sample-with-workerpool.yaml
  image-generation/README.md
Labels: ok-to-test, size/XL, approved

#20 add link to maas.io
  README.md
Labels: size/XS, approved

#21 add link to webinar
  README.md
Labels: approved

#22 more info
  README.md
Labels: size/XS, approved
