Repository spectrocloud/cluster-api-provider-maas, pull requests merged in 2023-05, with the labels that each got.

#58 PSS-2036: Update go
  Dockerfile
  go.mod
  go.sum
Labels: size/XS

#59 [rel] PSS-2036: Update go
  Dockerfile
  go.mod
  go.sum
Labels: size/XS

#62 Update provider tag in metadata.yaml
  go.mod
  go.sum
  metadata.yaml
Labels: size/S

#63 Main v1beta1 v2
  main.go
Labels: size/L

#64 server ip
  pkg/maas/scope/client.go
Labels: size/XS

#66 Updated template and examples
  examples/sample-cp-only.yaml
  examples/sample-with-workerpool.yaml
  templates/cluster-template.yaml
Labels: size/L

#67 make generate v1beta1
  Makefile
  api/v1alpha4/groupversion_info.go
  api/v1beta1/groupversion_info.go
  pkg/maas/client/mock/clienset_mock.go
Labels: needs-ok-to-test, size/M

#60 Main v1beta1
  Dockerfile
  Makefile
  api/v1alpha4/groupversion_info.go
  api/v1beta1/groupversion_info.go
  controllers/maasmachine_controller.go
  examples/sample-cp-only.yaml
  examples/sample-with-workerpool.yaml
  go.mod
  go.sum
  main.go
  metadata.yaml
  pkg/maas/client/mock/clienset_mock.go
  pkg/maas/machine/machine.go
  pkg/maas/machine/machine_test.go
  pkg/maas/scope/machine.go
  templates/cluster-template.yaml
Labels: size/XL

#68 Updated REDME for v1beta1
  README.md
Labels: size/M

#70 Updated image list
  README.md
Labels: size/S

#72 Updated readme and image-generation doc
  Makefile
  clusterctl-settings.json
  image-generation/README.md
  metadata.yaml
Labels: size/S

#74 Update image generation README
  README.md
  image-generation/README.md
Labels: size/L

#76 handle uppercase hostname and preferred subnet changes
  Makefile
  controllers/maascluster_controller.go
  pkg/maas/scope/cluster.go
  pkg/maas/scope/machine.go
Labels: needs-ok-to-test, size/M

#77 PCP 734 fix typo
  pkg/maas/scope/cluster.go
Labels: needs-ok-to-test, size/XS

#78 PCP 734 fix typo
  pkg/maas/scope/cluster.go
Labels: needs-ok-to-test, size/XS
